name: tps
description: Request tokens from TPS
inputs:
  tps-url:
    description: TPS endpoint URL
    default: https://tps.hc-integrations.de/
runs:
  using: composite
  steps:
    - run: |
        ci_token=$(curl --fail --retry 2 -s \
            -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=tps" \
            | jq -r .value)
        token="$(curl --fail --retry 2 -s -X POST -H "Authorization: Bearer $ci_token" ${{ inputs.tps-url }})"
        echo "::add-mask::$token"
        echo "HCLOUD_TOKEN=$token" >> "$GITHUB_ENV"
      shell: bash
