name: CI

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  verify-action:
    permissions:
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run tps-action
        uses: ./
        with:
          token: ${{ secrets.HCLOUD_TOKEN  }}

      - uses: hetznercloud/setup-hcloud@v1

      - run: hcloud server-type list
